package main

import (
	"log"
	"net/http"

	"github.com/jteeuwen/go-fsgen"
	"github.com/jteeuwen/vfsgen"
)

// Static FS generated by vfsgen
var FS *fsgen.FS

func main() {
	// Initialize the VFS
	if err := vfsgen.Init(FS); err != nil {
		log.Fatalf("error initializing VFS: %v", err)
	}

	// Serve static files
	http.Handle("/static/", http.StripPrefix("/static/", http.FileServer(FS)))

	// Serve the root index.html
	http.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
		http.ServeFile(w, r, "static/index.html")
	})

	log.Println("Listening on :8080")
	if err := http.ListenAndServe(":8080", nil); err != nil {
		log.Fatalf("error starting server: %v", err)
	}
}
